name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build m-gen Docker image
        run: docker build . --file docker/dev/m-gen/Dockerfile --tag registry.rangeray.ru:5000/app-m-gen:latest
      
      - name: Login to Docker registry
        run: docker login registry.rangeray.ru:5000 -u ${{secrets.REGISTRY_USER}} -p ${{secrets.REGISTRY_PASSWORD}}

      - name: Push to registry m-gen Docker image
        run: docker push registry.rangeray.ru:5000/app-m-gen:latest
